version: '3.8'
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/simple_api_db?schema=public
  #     - JWT_SECRET=dev-secret-key
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network
  #   command: sh -c "pnpm prisma:generate && pnpm start:dev"

  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=simple_api_db
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
